# Generated by Django 5.0.4 on 2024-11-21 15:27

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pet_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=200)),
                ('pettype', models.CharField(max_length=200)),
                ('petbreed', models.CharField(max_length=200)),
                ('petage', models.IntegerField()),
                ('petgender', models.CharField(max_length=200)),
                ('petdesc', models.CharField(max_length=200)),
                ('petpic', models.ImageField(blank=True, null=True, upload_to=myapp.models.filepath)),
            ],
        ),
    ]
