# Generated by Django 5.0.4 on 2024-11-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_data',
            name='useremail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
