# Generated by Django 5.0.4 on 2024-11-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pet_data_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_data',
            name='petcity',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
