# Generated by Django 5.0.4 on 2024-11-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_pet_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
